// convex/marketing/generator.ts
//
// Campaign generation:
//   1. Text  — HF Router chat completions (DeepSeek fallback) → platform captions
//   2. Image — HF Router SD3-medium                          → branded static visual
//   3. Video — fal.ai workflow (Kling multi-shot, prompt-only) → marketing clip
//
// The video step is a single fal.ai workflow call: the endpoint takes ONLY a
// `prompt` (no image input) and returns the finished clip. The prompt is a
// FitAI marketing angle — a user pain point paired with the app's value — so
// the clip sells the app, not generic gym content. Angles rotate per campaign.
//
// Every asset is saved to Convex File Storage and its storageId + public URL
// are recorded in the database (marketingAssets). Steps are isolated: when one
// step fails it is written to marketing_logs and the pipeline keeps going, so
// a text failure never blocks the image, and vice versa.
//
// All database writes go through convex/marketing/internals.ts (internal
// mutations) because actions cannot touch the database directly — and to keep
// this module free of self-referential `internal.*` imports.

import { v } from "convex/values";
import { action, ActionCtx, mutation, query } from "../_generated/server";
import { internal } from "../_generated/api";
import { Id } from "../_generated/dataModel";
import { chatCompletion, routeModel } from "../lib/models";
import { isMarketingDay } from "./schedule";

// HF retired the legacy api-inference.huggingface.co serverless API (late 2025).
// All HF inference now goes through the router (https://router.huggingface.co):
//  - text  -> OpenAI-compatible /v1/chat/completions (auto provider routing)
//  - image -> /hf-inference/models/{id} (HF Inference provider catalog)
// Video no longer uses HF at all — it is generated by the fal.ai workflow.
const HF_CHAT_URL = "https://router.huggingface.co/v1/chat/completions";
const HF_BASE = "https://router.huggingface.co/hf-inference/models";
const DEFAULT_TEXT_MODEL = "meta-llama/Llama-3.1-8B-Instruct";
const DEFAULT_IMAGE_MODEL = "stabilityai/stable-diffusion-3-medium-diffusers";
const DEFAULT_FAL_WORKFLOW_ENDPOINT =
  "https://fal.run/workflows/m0502369637-hub/kling-multi-shot-creator/stream";
const DEFAULT_BRAND_COLOR = "#d7f26d"; // FitAI chartreuse
const KNOWN_PLATFORMS = ["x", "facebook", "instagram", "linkedin"] as const;

/** The app link appended to every caption (overridable via APP_URL). */
function appLink(): string {
  return process.env.APP_URL ?? "https://t.me/FitAI_Training_bot";
}

/**
 * Guarantee the app link is present in a caption. X counts URLs against its
 * character budget, so the body is trimmed there instead of overflowing.
 */
function ensureAppLink(platform: string, caption: string): string {
  const link = appLink();
  if (caption.includes(link)) return caption;
  if (platform === "x") {
    const suffix = `\n\n👉 ${link}`;
    const maxBody = Math.max(0, 270 - suffix.length);
    return caption.slice(0, maxBody) + suffix;
  }
  return `${caption}\n\n👉 ${link}`;
}

/**
 * Strip unpaired UTF-16 surrogates (occasionally emitted by LLMs). Convex's
 * JSON codec rejects lone surrogates, so sanitize before any DB write.
 */
function sanitizeText(value: string): string {
  let out = "";
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(i + 1);
      if (next >= 0xdc00 && next <= 0xdfff) {
        out += value[i] + value[i + 1];
        i++;
      }
      // else: lone high surrogate — dropped
    } else if (code >= 0xdc00 && code <= 0xdfff) {
      // lone low surrogate — dropped
    } else {
      out += value[i];
    }
  }
  return out;
}

function finishCaption(platform: string, result: CaptionResult): CaptionResult {
  return {
    caption: sanitizeText(ensureAppLink(platform, result.caption)),
    hashtags: result.hashtags.map(sanitizeText),
  };
}

type LogLevel = "info" | "warn" | "error";
type CaptionResult = { caption: string; hashtags: string[] };
type Media = { bytes: ArrayBuffer; mime: string };

type GenerateResult =
  | { ok: true; campaignId: Id<"marketingCampaigns">; captions: Record<string, string>; errors: string[] }
  | { ok: false; reason: "MARKETING_DISABLED" | "NOT_MARKETING_DAY" }
  | { ok: false; campaignId: Id<"marketingCampaigns">; reason: "GENERATION_FAILED"; errors: string[] };

// ---------------------------------------------------------------------------
// Small helpers
// ---------------------------------------------------------------------------

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

function hfToken(): string {
  const token = process.env.HF_API_TOKEN ?? process.env.HF_TOKEN;
  if (!token) {
    throw new Error("HF_API_TOKEN is not set. Run `npx convex env set HF_API_TOKEN <token>`.");
  }
  return token;
}

/**
 * POST JSON to the HF Router with cold-start / rate-limit resilience:
 * `x-wait-for-model: true` makes HF hold the request while the model loads,
 * and 429/503/5xx responses (plus timeouts and network hiccups) are retried
 * with exponential backoff.
 */
async function hfRequest(
  url: string,
  body: unknown,
  options: { timeoutMs?: number; maxRetries?: number } = {},
): Promise<Response> {
  const timeoutMs = options.timeoutMs ?? 120_000;
  const maxRetries = options.maxRetries ?? 4;
  let lastError: Error | null = null;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    if (attempt > 0) await sleep(Math.min(1000 * 2 ** (attempt - 1), 15_000));
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${hfToken()}`,
          "Content-Type": "application/json",
          "x-wait-for-model": "true",
        },
        body: JSON.stringify(body),
        signal: controller.signal,
      });
      if (res.ok) return res;
      const snippet = (await res.text().catch(() => "")).slice(0, 300);
      if (res.status === 429 || res.status === 503 || res.status >= 500) {
        lastError = new Error(`HF ${res.status} (will retry): ${snippet}`);
        continue;
      }
      throw new Error(`HF ${res.status}: ${snippet}`);
    } catch (e) {
      if (e instanceof Error && e.name === "AbortError") {
        lastError = new Error(`HF request timed out after ${timeoutMs}ms`);
        continue;
      }
      if (e instanceof TypeError) {
        // fetch-level failure (network): transient, worth retrying
        lastError = e;
        continue;
      }
      throw e;
    } finally {
      clearTimeout(timer);
    }
  }
  throw lastError ?? new Error("HF request failed");
}

/** HF media endpoints return raw bytes OR JSON with a base64 field. Handle both. */
async function responseToBytes(res: Response): Promise<Media> {
  const contentType = res.headers.get("content-type") ?? "";
  if (contentType.includes("json")) {
    const data = (await res.json()) as unknown;
    const b64 =
      (data as { video?: unknown })?.video ??
      (data as { image?: unknown })?.image ??
      (data as { data?: unknown })?.data ??
      (data as { base64?: unknown })?.base64 ??
      (Array.isArray(data) ? (data[0] as { generated_video?: unknown })?.generated_video ?? null : null);
    if (typeof b64 !== "string" || b64.length === 0) {
      throw new Error("HF returned JSON without a base64 media field");
    }
    const prefix = b64.startsWith("data:") ? b64.split(";")[0] : "";
    const mime = prefix.split(":")[1] ?? "application/octet-stream";
    const bytes = base64ToBytes(b64);
    return { bytes: bytes.buffer as ArrayBuffer, mime };
  }
  return { bytes: await res.arrayBuffer(), mime: contentType.split(";")[0] || "application/octet-stream" };
}

function base64ToBytes(b64: string): Uint8Array {
  const cleaned = b64.replace(/^data:[^;]+;base64,/, "").replace(/\s+/g, "");
  if (typeof atob === "function") {
    const binary = atob(cleaned);
    const out = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
    return out;
  }
  // Manual fallback decoder for runtimes without atob.
  const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const padded = cleaned.replace(/=+$/, "");
  const out = new Uint8Array(Math.floor((padded.length * 3) / 4));
  let buffer = 0;
  let bits = 0;
  let index = 0;
  for (const ch of padded) {
    const val = ALPHABET.indexOf(ch);
    if (val === -1) continue;
    buffer = (buffer << 6) | val;
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      out[index++] = (buffer >> bits) & 0xff;
    }
  }
  return out;
}

function normalizePlatforms(raw: string[] | undefined): string[] {
  const known: readonly string[] = KNOWN_PLATFORMS;
  if (!raw || raw.length === 0) return [...known];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const p of raw) {
    if (known.includes(p) && !seen.has(p)) {
      seen.add(p);
      out.push(p);
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Prompts (the canonical copies live in convex/marketing/PROMPTS.md)
// ---------------------------------------------------------------------------

// All marketing POSTS are written in Arabic — specifically the warm Saudi
// white dialect (فصحى خفيفة مخلوطة بالعامية السعودية) so they read like a
// real Saudi person, not a machine. The video prompt (below) stays in English:
// video models follow English direction better, and the clip itself carries no
// text. Canonical copies live in convex/marketing/PROMPTS.md.

const TEXT_SYSTEM_PROMPT = [
  "أنت سعودي تكتب منشورات تسويقية لتطبيق FitAI، تطبيق لياقة مجاني داخل تيليجرام.",
  "اكتب باللهجة السعودية البيضاء: فصحى خفيفة مخلوطة بالعامية السعودية، كأنك تنصح صاحبك في الجلسة.",
  "استخدم كلمات عامية طبيعية مثل: الحين، وش تنتظر، مره، يالله، حماس، روق، عساك، ترى، ولا أحلى.",
  "اكتب كأن إنسان حقيقي كتبها — لا تبدو مكتوبة بالذكاء الاصطناعي.",
  "ممنوع: العبارات الجاهزة والمبالغات الإعلانية (مثل «ثورة في عالم اللياقة»، «لا تفوّت الفرصة»، «اكتشف السر»)، وممنوع كثرة الإيموجي.",
  "لا تكتب أي تفكير أو شرح — أخرج JSON فوراً.",
  'أجب بـ JSON فقط: {"caption":"...","hashtags":["..."]}.',
].join(" ");

const PLATFORM_TEXT_INSTRUCTIONS: Record<string, string> = {
  x: "المنصة: إكس (تويتر). اكتب تغريدة عفوية بلهجة سعودية، بحد أقصى 250 حرفاً. ابدأ بجملة توقف التمرير مثل «ترى …» أو «وش تنتظر؟». 2-3 وسمات فقط.",
  facebook:
    "المنصة: فيسبوك. اكتب منشوراً من 100-150 كلمة بأسلوب سوالف مع الأصدقاء، فيه نبرة سعودية دافية. اختم بسؤال يشجع التعليقات ودعوة خفيفة. 3-5 وسمات.",
  linkedin:
    "المنصة: لينكدإن. اكتب منشوراً احترافياً من 800-1100 حرف. افتتاحية قصة قصيرة، ثم ثلاث نقاط قيمة، ثم دعوة لطيفة. عربية فصيحة أقرب للرسمية مع لمسة عامية خفيفة جداً. 3 وسمات.",
  instagram:
    "المنصة: إنستغرام. اكتب كابشن حماسي بلهجة سعودية من 130-180 كلمة مع فواصل أسطر و2-3 إيموجي كحد أقصى. الدعوة: افتح FitAI على تيليجرام. 8-10 وسمات لياقة.",
  tiktok:
    "المنصة: تيك توك. اكتب وصفاً قصيراً بلهجة سعودية أقل من 140 حرفاً، ابدأ بأقوى جملة. 4-6 وسمات منها وسم لياقة رائج.",
};

function textUserPrompt(platform: string, theme: string, topic: string, brandColor: string): string {
  return [
    PLATFORM_TEXT_INSTRUCTIONS[platform],
    `موضوع الحملة: ${theme}.`,
    `الموضوع المركّز: ${topic}.`,
    `لون العلامة المميز: ${brandColor} (اذكره فقط إن كان طبيعياً).`,
    "اذكر بشكل خفيف أن FitAI تطبيق تيليجرام مجاني.",
    "اكتب بنبرة إنسان سعودي حقيقي — خفيفة، مباشرة، بدون مبالغات إعلانية.",
    "اختم الوصف دائماً برابط التطبيق: https://t.me/FitAI_Training_bot مع الالتزام بحد الطول لكل منصة.",
    'أجب بـ JSON فقط: {"caption":"...","hashtags":["..."]} بدون أي تنسيق إضافي.',
  ].join("\n");
}

/** Image prompt — English (generation prompts stay English; only the posted
 *  copy is Arabic). */
function imagePrompt(theme: string, topic: string, brandColor: string): string {
  return [
    "Cinematic fitness photograph,",
    theme,
    `featuring ${topic},`,
    `dominant accent color ${brandColor} on training apparel, gym equipment and rim lighting,`,
    "realistic Middle Eastern people, moody dark background, dramatic rim light, shallow depth of field, 35mm lens,",
    "ultra high resolution, professional sports advertising aesthetic,",
    "no text, no watermark, no logo",
  ].join(" ");
}

// ---------------------------------------------------------------------------
// Generation steps
// ---------------------------------------------------------------------------

/**
 * 1) Text: one caption per platform. DeepSeek writes far better Saudi Arabic,
 * so it is the primary model; the HF Router is the fallback when DeepSeek is
 * unavailable or fails (disable the fallback with MARKETING_TEXT_FALLBACK=off).
 */
async function generateCaption(
  platform: string,
  theme: string,
  topic: string,
  brandColor: string,
): Promise<CaptionResult> {
  const userPrompt = textUserPrompt(platform, theme, topic, brandColor);

  // --- Attempt 1: DeepSeek (best Arabic quality) ---
  const primary = routeModel({ vision: false });
  if (primary) {
    // The DeepSeek text model is a reasoning model: give it a generous token
    // budget so reasoning never starves the caption content.
    const cfg = { ...primary, maxTokens: 4000, temperature: 0.7 };
    let lastError: unknown = null;
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        const text = await chatCompletion(cfg, [
          { role: "system", content: TEXT_SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ]);
        return finishCaption(platform, parseCaption(text));
      } catch (err) {
        lastError = err;
      }
    }
    if (process.env.MARKETING_TEXT_FALLBACK === "off") {
      throw lastError instanceof Error ? lastError : new Error("DeepSeek caption generation failed");
    }
    // Fall through to the HF attempt.
  }

  // --- Attempt 2: Hugging Face router (auto provider selection) ---
  const model = process.env.MARKETING_TEXT_MODEL ?? DEFAULT_TEXT_MODEL;
  const res = await hfRequest(
    HF_CHAT_URL,
    {
      model,
      messages: [
        { role: "system", content: TEXT_SYSTEM_PROMPT },
        { role: "user", content: userPrompt },
      ],
      max_tokens: 700,
      temperature: 0.85,
    },
    { timeoutMs: 60_000, maxRetries: 2 },
  );
  const data = (await res.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const content = data.choices?.[0]?.message?.content?.trim();
  if (!content) throw new Error("HF chat returned empty content");
  return finishCaption(platform, parseCaption(content));
}

/** Parse the model's reply: prefer JSON, fall back to regex extraction, then raw text. */
function parseCaption(raw: string): CaptionResult {
  const cleaned = raw.replace(/```(?:json)?/g, "").trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  if (start !== -1 && end > start) {
    try {
      const parsed = JSON.parse(cleaned.slice(start, end + 1)) as {
        caption?: unknown;
        hashtags?: unknown;
      };
      const caption = typeof parsed.caption === "string" ? parsed.caption.trim() : "";
      const hashtags = Array.isArray(parsed.hashtags)
        ? parsed.hashtags
            .filter((h): h is string => typeof h === "string")
            .map((h) => h.replace(/^#/, "").trim())
        : [];
      if (caption) return { caption, hashtags };
    } catch {
      // Invalid JSON (e.g. literal newlines inside strings) — extract fields directly.
      const captionMatch = cleaned.match(/"caption"\s*:\s*"((?:[^"\\]|\\.)*)"/);
      if (captionMatch) {
        let caption = "";
        try {
          caption = (JSON.parse(`"${captionMatch[1]}"`) as string).trim();
        } catch {
          caption = captionMatch[1].trim();
        }
        const hashtags = [...cleaned.matchAll(/"hashtags"\s*:\s*\[([\s\S]*?)\]/g)]
          .flatMap((m) => [...m[1].matchAll(/"([^"]+)"/g)].map((t) => t[1].replace(/^#/, "").trim()))
          .filter(Boolean);
        if (caption) return { caption, hashtags };
      }
    }
  }
  // Truncated JSON — the model hit its token budget mid-string, possibly with
  // NO closing brace at all ({"caption":"Partial text…). Recover the text and
  // cut any trailing hashtags stub.
  const truncated = cleaned.match(/^\s*\{\s*"caption"\s*:\s*"([\s\S]*)$/);
  if (truncated) {
    let partial = truncated[1];
    const cut = partial.search(/(\\?"\s*,?\s*\\?"hashtags\s*\\?"|\\?"hashtags\s*\\?"\s*:)/);
    if (cut !== -1) partial = partial.slice(0, cut);
    partial = partial.replace(/[",}\s]+$/, "").trim();
    if (partial) return { caption: partial, hashtags: [] };
  }
  const hashtags = [...cleaned.matchAll(/#[\p{L}\p{N}_]+/gu)].map((m) => m[0].replace(/^#/, ""));
  return { caption: cleaned, hashtags };
}

/** 2) Image: HF Inference provider text-to-image (SD3-medium, free credits). */
async function generateImage(theme: string, topic: string, brandColor: string): Promise<Media> {
  const model = process.env.MARKETING_IMAGE_MODEL ?? DEFAULT_IMAGE_MODEL;
  const res = await hfRequest(
    `${HF_BASE}/${model}`,
    {
      inputs: imagePrompt(theme, topic, brandColor),
      parameters: { width: 1024, height: 1024 },
    },
    { timeoutMs: 180_000, maxRetries: 3 },
  );
  return await responseToBytes(res);
}

// ---------------------------------------------------------------------------
// Video prompt — FitAI marketing angles (pain point -> app value)
// ---------------------------------------------------------------------------
//
// The clip must market FitAI itself (its value proposition), NOT be a generic
// gym promo or a workout demonstration. Each campaign draws one angle from the
// pool below so consecutive drops stay fresh ("mix for marketing"): the story
// opens on a real user pain and resolves with the value FitAI delivers.

type MarketingAngle = { pain: string; value: string };

const MARKETING_ANGLES: MarketingAngle[] = [
  {
    pain: "A busy professional with no time for the gym, feeling guilty about it",
    value: "FitAI builds a personal plan in minutes that fits any schedule, right inside Telegram",
  },
  {
    pain: "Generic one-size-fits-all workout plans that never fit a real body",
    value: "FitAI builds a plan from your goal, level and timeline — and the AI adapts it as you go",
  },
  {
    pain: "Personal trainers and gym memberships being too expensive",
    value: "FitAI is an AI coach in your pocket for a fraction of the cost",
  },
  {
    pain: "Motivation dying after week one and progress fading away",
    value: "FitAI tracks every workout with streaks and progress charts that keep you going",
  },
  {
    pain: "A beginner who doesn't know which exercise to do or how to do it",
    value: "FitAI shows every exercise with step-by-step images and instructions",
  },
  {
    pain: "Training regularly but never knowing if you are actually improving",
    value: "FitAI turns every session into day/week/month progress analytics you can see",
  },
];

function pickMarketingAngle(): MarketingAngle {
  return MARKETING_ANGLES[Math.floor(Math.random() * MARKETING_ANGLES.length)];
}

/**
 * The prompt handed to the fal.ai workflow — the endpoint's ONLY input.
 * Kept in English: video models follow English direction best, and the clip
 * itself contains no text (captions carry the Arabic messaging).
 */
function videoMarketingPrompt(theme: string, topic: string): string {
  const angle = pickMarketingAngle();
  return [
    "Vertical 9:16 marketing video for FitAI, an AI-powered fitness coach mini app on Telegram that builds personalized workout plans, tracks daily progress and costs less than a gym membership.",
    `Story: ${angle.pain}.`,
    `Then show the resolution — ${angle.value}.`,
    topic ? `Campaign topic: ${topic}.` : "",
    theme ? `Campaign theme: ${theme}.` : "",
    "Visual style: cinematic, high-energy, moody dark background with lime-chartreuse #d7f26d accents, a hand holding a phone with the app open, modern and aspirational, fast-paced cuts, realistic Middle Eastern people.",
    "This is app marketing, not a gym promo: show the lifestyle pain turning into relief through the app — do not show a generic gym workout demonstration.",
    "No text, no captions, no watermark, no logos in the frame.",
  ]
    .filter(Boolean)
    .join(" ");
}

/**
 * 3) Video: one fal.ai workflow call. The endpoint takes ONLY `{prompt}` and
 * streams progress events until the clip is ready; the finished video URL is
 * downloaded and stored like every other asset.
 */
function isVideoUrl(value: unknown): value is string {
  return (
    typeof value === "string" && /^https?:\/\/\S+\.(mp4|webm|mov|m4v)(\?\S*)?$/i.test(value)
  );
}

/**
 * Recursively collect video URLs. Strings ending in a known video extension
 * are always accepted; any other http(s) URL is accepted only when it sits
 * under a video-ish key (`outputs`, `video`, `result`, `clip`, …) because fal
 * media URLs are sometimes extension-less.
 */
function collectVideoUrls(node: unknown, out: string[], inVideoKey = false): void {
  if (node == null) return;
  if (typeof node === "string") {
    if (isVideoUrl(node)) {
      out.push(node);
    } else if (
      inVideoKey &&
      /^https?:\/\//i.test(node) &&
      !/\.(png|jpe?g|webp|gif|svg|bmp|avif)(\?\S*)?$/i.test(node)
    ) {
      out.push(node);
    }
    return;
  }
  if (Array.isArray(node)) {
    for (const item of node) collectVideoUrls(item, out, inVideoKey);
    return;
  }
  if (typeof node === "object") {
    for (const [key, value] of Object.entries(node as Record<string, unknown>)) {
      const videoField = /^(video|videos|output|outputs|result|results|clip|clips|media|files?)$/i.test(key);
      collectVideoUrls(value, out, inVideoKey || videoField);
    }
  }
}

/**
 * Parse ONE workflow stream event (a single JSON line, possibly an SSE
 * `data:` frame). Returns the error or the newest video URL found in it.
 */
function parseFalEvent(chunk: string): { videoUrl?: string; error?: string } {
  let event: unknown;
  try {
    event = JSON.parse(chunk);
  } catch {
    return {}; // non-JSON progress/keepalive line
  }
  if (event && typeof event === "object") {
    const record = event as Record<string, unknown>;
    const rawError = record.error ?? record.detail;
    const error =
      typeof rawError === "string"
        ? rawError
        : rawError && typeof rawError === "object" && typeof (rawError as Record<string, unknown>).message === "string"
          ? ((rawError as Record<string, unknown>).message as string)
          : undefined;
    if (error) return { error };
    const urls: string[] = [];
    collectVideoUrls(event, urls);
    const videoUrl = urls[urls.length - 1]; // last URL in this event wins
    if (videoUrl) return { videoUrl };
  }
  return {};
}

async function falWorkflowGenerateVideo(prompt: string): Promise<Media> {
  const key = process.env.FAL_API_KEY;
  if (!key) {
    throw new Error("FAL_API_KEY is not set — the fal.ai workflow needs it (https://fal.ai)");
  }
  const endpoint = process.env.FAL_WORKFLOW_ENDPOINT ?? DEFAULT_FAL_WORKFLOW_ENDPOINT;
  // Convex actions are capped at 64 MB of memory AND ~10 minutes of wall time.
  // The timeout covers the entire streaming body read, and the stream is
  // parsed line by line (NDJSON / SSE) without buffering the whole response.
  const timeoutMs = Number(process.env.FAL_WORKFLOW_TIMEOUT_MS ?? "540000");
  // Drop frames larger than this instead of letting them exhaust memory
  // (e.g. a workflow that embeds base64 media in a progress event).
  const MAX_FRAME_BYTES = 8 * 1024 * 1024;

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(endpoint, {
      method: "POST",
      headers: { Authorization: `Key ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({ prompt }),
      signal: controller.signal,
    });
    if (!res.ok) {
      throw new Error(`fal workflow ${res.status}: ${(await res.text().catch(() => "")).slice(0, 300)}`);
    }

    const reader = res.body?.getReader();
    if (!reader) {
      // No streaming body (unusual) — parse it as one event.
      const parsed = parseFalEvent(await res.text());
      if (parsed.error) throw new Error(`fal workflow error: ${parsed.error.slice(0, 300)}`);
      if (!parsed.videoUrl) throw new Error("fal workflow completed without a video url");
      return await downloadWorkflowVideo(parsed.videoUrl);
    }

    const decoder = new TextDecoder();
    let buffer = "";
    let skipping = false; // currently dropping an oversized frame
    let videoUrl: string | undefined;
    let error: string | undefined;
    let events = 0;

    const handleLine = (rawLine: string) => {
      const line = rawLine.trim();
      if (!line) return;
      let chunk = line.startsWith("data:") ? line.slice(5).trim() : line;
      if (!chunk || chunk === "[DONE]") return;
      events++;
      const parsed = parseFalEvent(chunk);
      if (parsed.error) error = parsed.error;
      if (parsed.videoUrl) videoUrl = parsed.videoUrl; // last URL wins
    };

    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      if (!skipping && buffer.length > MAX_FRAME_BYTES) skipping = true;
      let nl: number;
      while ((nl = buffer.indexOf("\n")) !== -1) {
        const rawLine = buffer.slice(0, nl);
        buffer = buffer.slice(nl + 1);
        if (!skipping) handleLine(rawLine);
        skipping = false;
      }
      // While skipping an oversized frame, keep the buffer from growing.
      if (skipping && buffer.length > MAX_FRAME_BYTES) buffer = "";
    }
    buffer += decoder.decode(); // flush multibyte tail
    if (buffer.trim()) handleLine(buffer);

    if (error) throw new Error(`fal workflow error: ${error.slice(0, 300)}`);
    if (!videoUrl) {
      throw new Error(`fal workflow completed without a video url (${events} events parsed)`);
    }
    return await downloadWorkflowVideo(videoUrl);
  } catch (e) {
    if (e instanceof Error && e.name === "AbortError") {
      throw new Error(`fal workflow timed out after ${timeoutMs}ms`);
    }
    throw e;
  } finally {
    clearTimeout(timer);
  }
}

/** Download the finished clip and return its bytes. */
async function downloadWorkflowVideo(videoUrl: string): Promise<Media> {
  const videoRes = await fetch(videoUrl);
  if (!videoRes.ok) throw new Error(`fal video download ${videoRes.status}`);
  const bytes = await videoRes.arrayBuffer();
  if (bytes.byteLength === 0) throw new Error("fal video download returned 0 bytes");
  return { bytes, mime: "video/mp4" };
}

/** Store bytes in Convex File Storage and record the asset row. */
async function storeAsset(
  ctx: ActionCtx,
  campaignId: Id<"marketingCampaigns">,
  kind: "image" | "video",
  bytes: ArrayBuffer,
  mime: string,
): Promise<{ storageId: string; url: string | undefined }> {
  const storageId = await ctx.storage.store(new Blob([bytes], { type: mime }));
  const url = (await ctx.storage.getUrl(storageId)) ?? undefined;
  await ctx.runMutation(internal.marketing.internals.saveAsset, { campaignId, kind, storageId, url });
  return { storageId, url };
}

// ---------------------------------------------------------------------------
// Public action — the scheduled 18:00 Riyadh (15:00 UTC) entrypoint
// ---------------------------------------------------------------------------

/** Health check: probes the HF hosts reachable from the Convex runtime. */
export const pingHf = action({
  args: {},
  handler: async () => {
    const probe = async (label: string, url: string, init: RequestInit) => {
      try {
        const res = await fetch(url, init);
        const ct = res.headers.get("content-type") ?? "";
        const body = (await res.text().catch(() => "")).slice(0, 200);
        return { label, ok: res.ok, status: res.status, contentType: ct, body };
      } catch (e) {
        return {
          label,
          ok: false,
          error: String(e),
          errorName: e instanceof Error ? e.name : null,
          errorCtor: e instanceof Error ? e.constructor?.name : typeof e,
        };
      }
    };
    const token = process.env.HF_API_TOKEN ?? process.env.HF_TOKEN ?? "";
    const auth = { Authorization: `Bearer ${token}` };
    const results = await Promise.all([
      probe("whoami", "https://huggingface.co/api/whoami-v2", { method: "GET", headers: auth }),
      probe(
        "router-textgen",
        "https://router.huggingface.co/hf-inference/models/meta-llama/Llama-3-8B-Instruct",
        {
          method: "POST",
          headers: { "Content-Type": "application/json", ...auth },
          body: JSON.stringify({
            inputs: "Reply with exactly one word: hello",
            parameters: { max_new_tokens: 4, return_full_text: false },
          }),
        },
      ),
      probe(
        "router-chat-completions",
        "https://router.huggingface.co/hf-inference/v1/chat/completions",
        {
          method: "POST",
          headers: { "Content-Type": "application/json", ...auth },
          body: JSON.stringify({
            model: "meta-llama/Llama-3-8B-Instruct",
            messages: [{ role: "user", content: "Reply with exactly one word: hello" }],
            max_tokens: 4,
          }),
        },
      ),
    ]);
    return { results };
  },
});

// ---------------------------------------------------------------------------
// Public queries (dashboard/CLI inspection)
// ---------------------------------------------------------------------------

/** Latest campaigns, newest first (status, media URLs, captions, errors). */
export const listCampaigns = query({
  args: { limit: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const take = Math.min(args.limit ?? 10, 50);
    return await ctx.db.query("marketingCampaigns").order("desc").take(take);
  },
});

/** Per-channel delivery results for one campaign (status, error, external id). */
export const listCampaignDistributions = query({
  args: { campaignId: v.id("marketingCampaigns") },
  handler: async (ctx, { campaignId }) => {
    return await ctx.db
      .query("marketingDistributions")
      .withIndex("by_campaignId", (q) => q.eq("campaignId", campaignId))
      .collect();
  },
});

/** Audit trail for one campaign (generation/distribution/cleanup steps). */
export const listCampaignLogs = query({
  args: { campaignId: v.id("marketingCampaigns"), limit: v.optional(v.number()) },
  handler: async (ctx, args) => {
    const take = Math.min(args.limit ?? 50, 200);
    return await ctx.db
      .query("marketingLogs")
      .withIndex("by_campaignId", (q) => q.eq("campaignId", args.campaignId))
      .order("desc")
      .take(take);
  },
});

/** One campaign by id (full document). */
export const getCampaign = query({
  args: { campaignId: v.id("marketingCampaigns") },
  handler: async (ctx, { campaignId }) => {
    return await ctx.db.get(campaignId);
  },
});

/**
 * Diagnostic: fetch the input schema of one Composio v3 tool so the exact
 * argument names can be verified without trial-and-error posting.
 */
export const debugComposioTool = action({
  args: { toolSlug: v.string() },
  handler: async (_ctx, { toolSlug }) => {
    const apiKey = process.env.COMPOSIO_API_KEY;
    if (!apiKey) return { error: "COMPOSIO_API_KEY not set" };
    const res = await fetch(
      `https://backend.composio.dev/api/v3.1/tools/${encodeURIComponent(toolSlug)}`,
      { headers: { "x-api-key": apiKey } },
    );
    const body = await res.text().catch(() => "");
    let parsed: unknown = null;
    try {
      parsed = JSON.parse(body);
    } catch {
      // keep raw text
    }
    return {
      status: res.status,
      body: body.slice(0, 20000),
      parsed: JSON.stringify(parsed ?? null).slice(0, 20000),
    };
  },
});

/**
 * Cancel a campaign before distribution: marks it "failed" so the distributor
 * never picks it up (the nightly cleanup will sweep its assets later).
 * Used to retire stale/undesired campaigns from the CLI or dashboard.
 */
export const cancelCampaign = mutation({
  args: {
    campaignId: v.id("marketingCampaigns"),
    reason: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const campaign = await ctx.db.get(args.campaignId);
    if (!campaign) return { ok: false, reason: "NOT_FOUND" };
    if (campaign.status === "completed" || campaign.status === "failed") {
      return { ok: false, reason: "ALREADY_FINAL" };
    }
    await ctx.db.patch(args.campaignId, {
      status: "failed",
      error: args.reason ?? "Cancelled by admin",
    });
    return { ok: true };
  },
});

export const generateCampaign = action({
  args: {
    theme: v.optional(v.string()),
    topic: v.optional(v.string()),
    brandColor: v.optional(v.string()),
    platforms: v.optional(v.array(v.string())),
    // When set by the daily cron, generation only runs on marketing days
    // (Tue/Thu/Sat Riyadh). Manual runs leave it unset and always execute.
    respectSchedule: v.optional(v.boolean()),
  },
  handler: async (ctx, args): Promise<GenerateResult> => {
    // Master switch: the engine stays dormant until MARKETING_ENABLED === "true".
    if (process.env.MARKETING_ENABLED !== "true") {
      return { ok: false, reason: "MARKETING_DISABLED" };
    }
    // Three drops a week: Tue / Thu / Sat (Riyadh). The cron fires daily and
    // passes respectSchedule so other days become a no-op.
    if (args.respectSchedule && !isMarketingDay()) {
      return { ok: false, reason: "NOT_MARKETING_DAY" };
    }

    const theme = args.theme ?? process.env.MARKETING_THEME ?? "تحول لياقي خلال 30 يوماً";
    const topic = args.topic ?? process.env.MARKETING_TOPIC ?? "تمارين منزلية سريعة بدون معدات";
    const brandColor = args.brandColor ?? process.env.MARKETING_BRAND_COLOR ?? DEFAULT_BRAND_COLOR;
    const platforms = normalizePlatforms(args.platforms);

    const campaignId = await ctx.runMutation(internal.marketing.internals.createCampaign, {
      theme,
      topic,
      brandColor,
      platforms,
    });
    const log = (level: LogLevel, source: string, message: string) =>
      ctx.runMutation(internal.marketing.internals.log, { campaignId, level, source, message });

    await log("info", "generator", `Campaign started: theme="${theme}" platforms=${platforms.join(",")}`);
    const errors: string[] = [];

    // --- Step 1: captions ---------------------------------------------------
    const captions: Record<string, string> = {};
    const hashtags: string[] = [];
    let hfAvailable = true;
    try {
      hfToken();
    } catch (e) {
      hfAvailable = false;
      errors.push(errMsg(e));
      await log("error", "generator.text", errMsg(e));
    }
    if (hfAvailable) {
      for (const platform of platforms) {
        try {
          const { caption, hashtags: tags } = await generateCaption(platform, theme, topic, brandColor);
          captions[platform] = caption;
          for (const tag of tags) {
            if (!hashtags.includes(tag)) hashtags.push(tag);
          }
          await log("info", `generator.text.${platform}`, `Caption ready (${caption.length} chars)`);
        } catch (e) {
          errors.push(`text/${platform}: ${errMsg(e)}`);
          await log("error", `generator.text.${platform}`, errMsg(e));
        }
      }
    }
    await ctx.runMutation(internal.marketing.internals.updateCampaign, {
      campaignId,
      captions,
      hashtags,
    });

    // --- Step 2: image (static branded visual for photo posts) --------------
    let image: Media | null = null;
    if (hfAvailable) {
      try {
        image = await generateImage(theme, topic, brandColor);
        const saved = await storeAsset(ctx, campaignId, "image", image.bytes, image.mime);
        await ctx.runMutation(internal.marketing.internals.updateCampaign, {
          campaignId,
          imageStorageId: saved.storageId,
          imageUrl: saved.url,
        });
        await log("info", "generator.image", `Image stored: ${saved.storageId}`);
      } catch (e) {
        errors.push(`image: ${errMsg(e)}`);
        await log("error", "generator.image", errMsg(e));
      }
    }

    // --- Step 3: video (fal.ai workflow — prompt-only, marketing angle) ------
    // Independent of the image step: the workflow takes a prompt, not an image.
    let video: Media | null = null;
    try {
      video = await falWorkflowGenerateVideo(videoMarketingPrompt(theme, topic));
      const saved = await storeAsset(ctx, campaignId, "video", video.bytes, video.mime);
      await ctx.runMutation(internal.marketing.internals.updateCampaign, {
        campaignId,
        videoStorageId: saved.storageId,
        videoUrl: saved.url,
      });
      await log("info", "generator.video", `Video stored: ${saved.storageId}`);
    } catch (e) {
      errors.push(`video: ${errMsg(e)}`);
      await log("error", "generator.video", errMsg(e));
    }

    // --- Finalize -----------------------------------------------------------
    const hasContent =
      Object.values(captions).some((c) => c.length > 0) || image !== null || video !== null;
    if (hasContent) {
      await ctx.runMutation(internal.marketing.internals.updateCampaign, {
        campaignId,
        status: "ready",
        generatedAt: Date.now(),
      });
      await log("info", "generator", "Campaign ready for distribution");
      return { ok: true, campaignId, captions, errors };
    }
    await ctx.runMutation(internal.marketing.internals.updateCampaign, {
      campaignId,
      status: "failed",
      error: errors.join("; ") || "No content generated",
    });
    await log("error", "generator", "Campaign failed: no captions, image or video");
    return { ok: false, campaignId, reason: "GENERATION_FAILED", errors };
  },
});
